// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (sql.NullString, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
